# Generated by Django 6.0.3 on 2026-05-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('users', '0001_initial'), ('users', '0002_student_universities'), ('users', '0003_remove_student_universities_student_degree'), ('users', '0004_student_universities'), ('users', '0005_student_is_admin'), ('users', '0005_remove_student_universities'), ('users', '0006_merge_20260501_1312')]

    initial = True

    dependencies = [
        ('courses', '0002_degree_university_year_degree_degree_university_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/')),
                ('degree', models.ManyToManyField(blank=True, to='courses.degree')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['first_name', 'last_name'], name='users_stude_first_n_64f682_idx')],
            },
        ),
    ]
