# Generated by Django 6.0.3 on 2026-04-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_universities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='universities',
        ),
    ]
