# Generated by Django 6.0.3 on 2026-04-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_student_universities"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
    ]
