# Generated by Django 6.0.3 on 2026-05-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_student_universities'),
        ('users', '0005_student_is_admin'),
    ]

    operations = [
    ]
