"""
Django settings for edutech project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
env = environ.Env(DEBUG=(bool, False))

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

# Accepts a comma-separated list via ALLOWED_HOSTS env var.
ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1", "web", "edutech-app.tail6b7334.ts.net"],
)

# CORS: static origins + any extras from env.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://127.0.0.1:5173",
    "http://localhost:8000",
    "https://edutech-app.tail6b7334.ts.net",
] + env.list("CORS_EXTRA_ORIGINS", default=[])
CORS_ALLOW_ALL_ORIGINS = DEBUG
X_FRAME_OPTIONS = "ALLOWALL"
CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "rest_framework",
    "corsheaders",
    "storages",
    "treebeard",
    "users",
    "courses",
    "ai_agent",
    "documents.apps.DocumentsConfig",
    "student_space",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.edutech.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ASGI_APPLICATION = "backend.edutech.asgi.application"

REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    # MicrosoftAuthentication reads the Bearer token sent by MSAL on the frontend,
    # calls Microsoft Graph to verify it, and sets request.user.
    # Returns None (anonymous) if no token is present, so unauthenticated endpoints
    # keep working. Raises 401 if a token IS present but invalid/expired.
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "users.authentication.MicrosoftAuthentication",
    ],
    # AllowAny globally — existing views work without a token.
    # Add permission_classes = [IsAuthenticated] to individual views that need it.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
}

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
] + env.list("CSRF_EXTRA_ORIGINS", default=[])


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db(),
}


# R2 Storage Configuration

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
AWS_S3_ENDPOINT_URL = env("R2_ENDPOINT_URL")
AWS_ACCESS_KEY_ID = env("R2_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env("R2_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = env("R2_BUCKET_NAME")
AWS_S3_REGION_NAME = "auto"
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = True
AWS_SIGNATURE_VERSION = "s3v4"


# SMTP Configuration
EMAIL_BACKEND = env(
    "EMAIL_BACKEND", default="django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


AI_SETTINGS = {
    "EMBEDDING_URL": os.environ.get(
        "EMBEDDING_URL", "http://host.docker.internal:11434"
    ),
    "EMBEDDING_MODEL": os.environ.get("EMBEDDING_MODEL", "nomic-embed-text"),
    "VISION_URL": os.environ.get("VISION_URL", "http://host.docker.internal:11434"),
    "VISION_MODEL": os.environ.get("VISION_MODEL", "gemma3:4b"),
    "CODE_DETECT_URL": os.environ.get(
        "CODE_DETECT_URL", "http://host.docker.internal:11434"
    ),
    "CODE_DETECT_MODEL": os.environ.get("CODE_DETECT_MODEL", "llama3.2"),
    "CHAT_URL": os.environ.get("CHAT_URL", "http://host.docker.internal:11434"),
    "CHAT_MODEL": os.environ.get("CHAT_MODEL", "gemma3:4b"),
    "VECTOR_DB_COLLECTION": "apuntes_universidad",
}

# ==========================================
# CONFIGURACIÓN DE CELERY Y REDIS
# ==========================================
# Dónde está el mensajero (Redis) que guarda la cola de tareas
CELERY_BROKER_URL = env("REDIS_URL", default="redis://redis:6379/0")

# Dónde guarda Celery el resultado de la tarea cuando termina
CELERY_RESULT_BACKEND = env("REDIS_URL", default="redis://redis:6379/0")

# Forzamos a que Celery acepte formato JSON al comunicarse
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# Django's cache framework backed by Redis.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": env("REDIS_URL", default="redis://redis:6379/1"),
    }
}

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                ("redis", 6379)
            ],  # Apunta al servicio 'redis' de tu docker-compose
        },
    },
}
