# Generated by Django 6.0.3 on 2026-05-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study_sessions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studysession",
            name="status",
            field=models.CharField(
                choices=[
                    ("proxima", "Próxima"),
                    ("en_directo", "En directo"),
                    ("finalizada", "Finalizada"),
                ],
                default="proxima",
                max_length=20,
            ),
        ),
    ]
