# Generated by Django 6.0.3 on 2026-04-01 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('post_type', models.CharField(choices=[('PDF', 'Documento PDF'), ('VID', 'Vídeo de YouTube')], max_length=3)),
                ('content_url', models.URLField(blank=True, max_length=500, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.post')),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.post')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'post'], name='documents_l_user_id_530490_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='DisLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.post')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'post'], name='documents_d_user_id_2ff50b_idx')],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
