# Generated by Django 6.0.3 on 2026-05-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_courses_cou_name_eb4cc3_idx_and_more'),
        ('documents', '0001_initial'),
        ('users', '0002_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dislike',
            name='documents_d_user_id_553b09_idx',
        ),
        migrations.RemoveIndex(
            model_name='like',
            name='documents_l_user_id_a3eed4_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='documents_p_course__396f2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='documents_p_student_de4a44_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dislike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='answer',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', '-created_at'], name='documents_c_post_id_308b24_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['course', 'post_type', '-created_at'], name='documents_p_course__38c931_idx'),
        ),
        migrations.AddConstraint(
            model_name='dislike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_dislike'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_like'),
        ),
    ]
