from django.db import migrations


def create_tables(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("""
        ALTER TABLE documents_post ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT NOW();

        CREATE TABLE IF NOT EXISTS documents_reportreason (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reason character varying(200) NOT NULL
        );
        CREATE TABLE IF NOT EXISTS documents_flashcarddeck (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            post_id bigint NOT NULL UNIQUE REFERENCES documents_post(id) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS documents_flashcard (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            question text NOT NULL,
            answer text NOT NULL,
            deck_id bigint NOT NULL REFERENCES documents_flashcarddeck(id) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS documents_quiz (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            post_id bigint NOT NULL UNIQUE REFERENCES documents_post(id) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS documents_question (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title character varying(500) NOT NULL,
            quiz_id bigint NOT NULL REFERENCES documents_quiz(id) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS documents_answer (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            text character varying(500) NOT NULL,
            is_correct boolean NOT NULL DEFAULT FALSE,
            question_id bigint NOT NULL REFERENCES documents_question(id) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS documents_report (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            description text NOT NULL,
            created_at timestamp with time zone NOT NULL,
            post_id bigint NOT NULL REFERENCES documents_post(id) ON DELETE CASCADE,
            reason_id bigint NOT NULL REFERENCES documents_reportreason(id) ON DELETE CASCADE,
            user_id bigint NOT NULL REFERENCES users_student(id) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS documents_reportresolution (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            message text NOT NULL,
            created_at timestamp with time zone NOT NULL,
            report_id bigint NOT NULL UNIQUE REFERENCES documents_report(id) ON DELETE CASCADE,
            resolved_by_id bigint REFERENCES users_student(id) ON DELETE SET NULL
        );
        CREATE TABLE IF NOT EXISTS documents_commentreport (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            description text NOT NULL,
            created_at timestamp with time zone NOT NULL,
            comment_id bigint NOT NULL REFERENCES documents_comment(id) ON DELETE CASCADE,
            reason_id bigint NOT NULL REFERENCES documents_reportreason(id) ON DELETE CASCADE,
            user_id bigint NOT NULL REFERENCES users_student(id) ON DELETE CASCADE
        );
    """)


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunPython(create_tables, migrations.RunPython.noop),
            ],
        ),
    ]
