# Generated by Django 6.0.3 on 2026-04-07 09:50

import django.db.models.deletion
import django.utils.timezone
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_subscriptions_subscription_and_more'),
        ('documents', '0001_initial'),
        ('users', '0002_alter_student_options_student_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PDFAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/', validators=[documents.models.validate_pdf_extension, documents.models.validate_pdf_size])),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Liked',
            new_name='Dislike',
        ),
        migrations.RenameModel(
            old_name='DisLikes',
            new_name='Like',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='assignment',
            new_name='course',
        ),
        migrations.RenameIndex(
            model_name='dislike',
            new_name='documents_d_user_id_553b09_idx',
            old_name='documents_l_user_id_530490_idx',
        ),
        migrations.RenameIndex(
            model_name='like',
            new_name='documents_l_user_id_a3eed4_idx',
            old_name='documents_d_user_id_2ff50b_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_url',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['course', 'post_type'], name='documents_p_course__396f2b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['student'], name='documents_p_student_de4a44_idx'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='pdfattachment',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdf', to='documents.post'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vid', to='documents.post'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
