# Generated by Django 6.0.3 on 2026-04-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20260414_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfattachment',
            name='processing_status',
            field=models.CharField(choices=[('subiendo', 'Subiendo fichero...'), ('reconociendo_img', 'Reconociendo imágenes...'), ('extrayendo_txt', 'Extrayendo texto...'), ('vectorizando', 'Vectorizando...'), ('completado', '¡Listo para IA!'), ('error', 'Error en el procesamiento')], default='subiendo', max_length=20),
        ),
    ]
