# Generated by Django 6.0.3 on 2026-05-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_pdfattachment_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ai_gen',
            field=models.BooleanField(default=False),
        ),
    ]
