# Generated by Django 6.0.3 on 2026-04-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0002_alter_student_options_student_picture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriptions',
            new_name='Subscription',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='assignment',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'year', 'semester')},
        ),
    ]
