# Generated by Django 6.0.3 on 2026-04-29 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('location', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='year',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.degree'),
        ),
        migrations.AddField(
            model_name='degree',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.university'),
        ),
        migrations.AlterUniqueTogether(
            name='degree',
            unique_together={('name', 'university')},
        ),
    ]
