# Generated by Django 6.0.3 on 2026-05-01 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
        migrations.AddField(
            model_name='degree',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.university'),
        ),
        migrations.AddField(
            model_name='year',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.degree'),
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.year'),
        ),
        migrations.AlterUniqueTogether(
            name='degree',
            unique_together={('name', 'university')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name'], name='courses_cou_name_eb4cc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'year', 'semester')},
        ),
    ]
