from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    CREATE TABLE IF NOT EXISTS courses_studysession (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title character varying(200) NOT NULL,
                        description text NOT NULL DEFAULT '',
                        scheduled_at timestamp with time zone NOT NULL,
                        created_at timestamp with time zone NOT NULL,
                        course_id bigint REFERENCES courses_course(id) ON DELETE CASCADE,
                        creator_id bigint NOT NULL REFERENCES users_student(id) ON DELETE CASCADE
                    );
                    CREATE TABLE IF NOT EXISTS courses_studysession_participants (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        studysession_id bigint NOT NULL REFERENCES courses_studysession(id) ON DELETE CASCADE,
                        student_id bigint NOT NULL REFERENCES users_student(id) ON DELETE CASCADE,
                        UNIQUE (studysession_id, student_id)
                    );
                    CREATE TABLE IF NOT EXISTS courses_studysessioncomment (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        message text NOT NULL,
                        created_at timestamp with time zone NOT NULL,
                        session_id bigint NOT NULL REFERENCES courses_studysession(id) ON DELETE CASCADE,
                        student_id bigint NOT NULL REFERENCES users_student(id) ON DELETE CASCADE
                    );
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
