# Generated by Django 6.0.3 on 2026-04-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_degree_university_year_degree_degree_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='logo_universities/'),
        ),
    ]
