# Generated by Django 6.0.3 on 2026-05-12 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_create_missing_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studysessioncomment',
            name='session',
        ),
        migrations.RemoveField(
            model_name='studysessioncomment',
            name='student',
        ),
        migrations.DeleteModel(
            name='StudySession',
        ),
        migrations.DeleteModel(
            name='StudySessionComment',
        ),
    ]
