# Generated by Django 6.0.3 on 2026-05-01 22:31

import django.db.models.deletion
from django.db import migrations, models

CREATE_SQL = """
    CREATE TABLE IF NOT EXISTS "courses_studysession" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "title" varchar(200) NOT NULL,
        "description" text NOT NULL,
        "scheduled_at" timestamp with time zone NOT NULL,
        "created_at" timestamp with time zone NOT NULL,
        "course_id" bigint NULL
            REFERENCES "courses_course" ("id") DEFERRABLE INITIALLY DEFERRED,
        "creator_id" bigint NOT NULL
            REFERENCES "users_student" ("id") DEFERRABLE INITIALLY DEFERRED
    );
    CREATE INDEX IF NOT EXISTS "courses_studysession_course_id"
        ON "courses_studysession" ("course_id");
    CREATE INDEX IF NOT EXISTS "courses_studysession_creator_id"
        ON "courses_studysession" ("creator_id");

    CREATE TABLE IF NOT EXISTS "courses_studysession_participants" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "studysession_id" bigint NOT NULL
            REFERENCES "courses_studysession" ("id") DEFERRABLE INITIALLY DEFERRED,
        "student_id" bigint NOT NULL
            REFERENCES "users_student" ("id") DEFERRABLE INITIALLY DEFERRED,
        UNIQUE ("studysession_id", "student_id")
    );
    CREATE INDEX IF NOT EXISTS "courses_studysession_participants_studysession_id"
        ON "courses_studysession_participants" ("studysession_id");
    CREATE INDEX IF NOT EXISTS "courses_studysession_participants_student_id"
        ON "courses_studysession_participants" ("student_id");

    CREATE TABLE IF NOT EXISTS "courses_studysessioncomment" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "message" text NOT NULL,
        "created_at" timestamp with time zone NOT NULL,
        "session_id" bigint NOT NULL
            REFERENCES "courses_studysession" ("id") DEFERRABLE INITIALLY DEFERRED,
        "student_id" bigint NOT NULL
            REFERENCES "users_student" ("id") DEFERRABLE INITIALLY DEFERRED
    );
    CREATE INDEX IF NOT EXISTS "courses_studysessioncomment_session_id"
        ON "courses_studysessioncomment" ("session_id");
    CREATE INDEX IF NOT EXISTS "courses_studysessioncomment_student_id"
        ON "courses_studysessioncomment" ("student_id");
"""

DROP_SQL = """
    DROP TABLE IF EXISTS "courses_studysessioncomment";
    DROP TABLE IF EXISTS "courses_studysession_participants";
    DROP TABLE IF EXISTS "courses_studysession";
"""


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_add_university_logo"),
        ("users", "0002_alter_student_options_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="StudySession",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("title", models.CharField(max_length=200)),
                        ("description", models.TextField(blank=True)),
                        ("scheduled_at", models.DateTimeField()),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "course",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="study_sessions",
                                to="courses.course",
                            ),
                        ),
                        (
                            "creator",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="study_sessions",
                                to="users.student",
                            ),
                        ),
                        (
                            "participants",
                            models.ManyToManyField(
                                blank=True,
                                related_name="participating_sessions",
                                to="users.student",
                            ),
                        ),
                    ],
                    options={"ordering": ["scheduled_at"]},
                ),
                migrations.CreateModel(
                    name="StudySessionComment",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("message", models.TextField()),
                        ("created_at", models.DateTimeField(auto_now_add=True)),
                        (
                            "session",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="session_comments",
                                to="courses.studysession",
                            ),
                        ),
                        (
                            "student",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="study_session_comments",
                                to="users.student",
                            ),
                        ),
                    ],
                    options={"ordering": ["created_at"]},
                ),
            ],
            database_operations=[
                migrations.RunSQL(sql=CREATE_SQL, reverse_sql=DROP_SQL),
            ],
        ),
    ]
