# Generated by Django 6.0.3 on 2026-05-01 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_university_logo'),
        ('users', '0002_alter_student_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='StudySession',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=200)),
                        ('description', models.TextField(blank=True)),
                        ('scheduled_at', models.DateTimeField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='courses.course')),
                        ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='users.student')),
                        ('participants', models.ManyToManyField(blank=True, related_name='participating_sessions', to='users.student')),
                    ],
                    options={
                        'ordering': ['scheduled_at'],
                    },
                ),
                migrations.CreateModel(
                    name='StudySessionComment',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('message', models.TextField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_comments', to='courses.studysession')),
                        ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_session_comments', to='users.student')),
                    ],
                    options={
                        'ordering': ['created_at'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
