# Generated by Django 6.0.3 on 2026-05-01 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_studysession_participants_studysessioncomment"),
        ("users", "0005_student_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_sessions",
                to="users.student",
            ),
        ),
    ]
