# Generated by Django 6.0.3 on 2026-05-01 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_studysession_creator"),
        ("users", "0005_student_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studysession",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_sessions",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_sessions",
                to="users.student",
            ),
            preserve_default=False,
        ),
    ]
