# Generated by Django 6.0.3 on 2026-05-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_space", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedpost",
            name="is_pinned",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="savedpost",
            name="pinned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
